# built and published from https://github.com/cse-labs/codespaces-images

FROM ghcr.io/cse-labs/k3d-wasm:latest

ARG USERNAME=vscode

# add additional setup here
RUN wget https://get.radapp.dev/tools/vscode/stable/rad-vscode-bicep.vsix -O /home/$USERNAME/rad-vscode-bicep.vsix
